"""Quality / regression suite for auto_negadoctor.

Iterates over every annotated roll under tests/fixtures/rolls/ that has local
TIFF exports (discover_rolls), running two layers per roll:
  1. Baseline-independent INVARIANTS over a fresh pipeline run (param ranges,
     wb normalization, exposure-ordering consistency of Dmin across frames,
     patches inside frame bounds and outside the holder border, hex round-trip),
     plus the crop-containment / ground-truth / AI-variant / no-clipping gates
     against that roll's committed annotations.
  2. Baseline diff vs tests/baseline_session/<roll_id>/{stem}_debug_nega.json
     (generated by generate_baseline.py after user approval): global winner
     identity, film-base location, params within tolerances.

Run: conda run -n autocrop python auto_negadoctor/tests/run_quality_tests.py
Exit code: 0 = PASS or WARN, 1 = FAIL.
"""

import json
import math
import os
import sys
from pathlib import Path

TESTS_DIR = Path(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, str(TESTS_DIR.parent))
import auto_negadoctor as an
import nega_model as nm

IMAGES_DIR = TESTS_DIR / "images"            # legacy sRGB JPEG fallback fixtures
ROLLS_DIR = TESTS_DIR / "fixtures" / "rolls"  # one folder per annotated roll:
# its TIFFs (gitignored) + exif_params.txt + scene_labels.json + annotation
# sessions all live together under fixtures/rolls/<roll_id>/.
BASELINE_DIR = TESTS_DIR / "baseline_session"


def discover_rolls():
    """Every annotated-roll folder under fixtures/rolls/ that has local TIFF
    exports. The roll id is the folder name; the heavy linear-Rec2020 TIFFs are
    gitignored and regenerated from the source raws (see fixtures/rolls/
    README.md), so a roll with committed annotations but no local TIFFs is
    skipped here. Returns a list of dicts:
        {id, dir, images: [path], exif: {stem: ...}, fixtures: [Path]}
    Annotation sessions may be dated subfolders (multiple per stem) or flat, so
    the fixtures are gathered with rglob."""
    rolls = []
    if not ROLLS_DIR.is_dir():
        return rolls
    for d in sorted(p for p in ROLLS_DIR.iterdir() if p.is_dir()):
        tifs = sorted(d.glob("*.tif"))
        if not tifs:
            continue
        exif_path = d / "exif_params.txt"
        exif = an.parse_exif_params(str(exif_path)) if exif_path.is_file() else {}
        rolls.append({
            "id": d.name,
            "dir": d,
            "images": [str(p) for p in tifs],
            "exif": exif,
            "fixtures": sorted(d.rglob("*_annotations.json")),
        })
    return rolls

# Baseline diff tolerances (deterministic pipeline; slack covers const tweaks)
TOL_DMIN_REL = 0.10
TOL_DMAX = 0.20
TOL_WB = 0.10
TOL_BLACK = 0.05
TOL_EXPOSURE = 0.05
TOL_PATCH_CENTER_PX = 30.0
TOL_PATCH_SIZE_PX = 10
# Verdict gates: fraction of frames allowed to differ from baseline
PASS_DIFF_FRAC = 0.10
WARN_DIFF_FRAC = 0.30

WB_NORM_EPS = 1e-3
EXPOSURE_ORDER_REL_TOL = 0.02   # Dmin_i/Dmin_j vs factor_i/factor_j
CROP_CONTAINMENT_ROUND_TOL = 1  # px slack for cross-resolution crop denorm

# Ground-truth gate tolerances (the user's wheel/print annotations are the
# target the production algorithm must converge to). Deliberately strict; the
# gate is expected to FAIL until the wb finder + print tune (+ PRINT_GAMMA) are
# tuned to match. Loosen ONLY with the user's sign-off.
TOL_GT_WB = 0.05         # abs delta per wb_low/wb_high component
TOL_GT_BLACK = 0.03
TOL_GT_EXPOSURE = 0.05
TOL_GT_GAMMA = 0.10

# Hard-clip gate: the param gate does NOT measure clipping, yet a tuner that
# matches the param values can still blow out the highlights (a shadow-anchor
# attempt clipped 3-60% of pixels on normal scenes — the user reported it
# unusable on re-export). Rendering the user's own GT params clips ~0% on every
# frame, so the production print tune must too.
CLIP_OUT_THR = 0.999     # rendered output at/above this = a hard-clipped pixel
CLIP_MAX_FRAC = 0.01     # max fraction of hard-clipped pixels allowed per frame

# Annotation crop rects are stored as NORMALIZED fractions of the frame
# (resolution-independent). Legacy pixel rects (any coord > 1.5) pass through.
def _rect_to_px(rect, w, h):
    """[x, y, rw, rh] fractions -> integer pixels (legacy px rects unchanged)."""
    if max(abs(float(v)) for v in rect) > 1.5:
        return [int(round(float(v))) for v in rect]
    x, y, rw, rh = rect
    return [int(round(x * w)), int(round(y * h)),
            int(round(rw * w)), int(round(rh * h))]


# Annotation fixtures are ROLL-SCOPED by directory: each roll's annotation
# sessions live under its own fixtures/rolls/<roll_id>/ folder alongside its
# images, so stems that collide across rolls (every roll has a DSC_0013) never
# cross-contaminate — discover_rolls() hands each roll only its own fixtures.


# ---------------------------------------------------------------------------
# Invariants (baseline-independent)
# ---------------------------------------------------------------------------

def check_frame_invariants(frames, roll):
    """Return a list of violation strings (empty = all good)."""
    bad = []

    def chk(cond, stem, msg):
        if not cond:
            bad.append(f"{stem}: {msg}")

    ok_frames = [f for f in frames if not f.get("error") and f.get("params")]
    for fr in ok_frames:
        stem = fr["stem"]
        p = fr["params"]

        for name, val, rng in (
            ("D_max", p["D_max"], nm.DMAX_RANGE),
            ("offset", p["offset"], nm.OFFSET_RANGE),
            ("black", p["black"], nm.BLACK_RANGE),
            ("exposure", p["exposure"], nm.EXPOSURE_RANGE),
        ):
            chk(math.isfinite(val) and rng[0] <= val <= rng[1], stem,
                f"{name}={val} outside {rng}")
        for c in range(3):
            chk(nm.DMIN_RANGE[0] <= p["Dmin"][c] <= nm.DMIN_RANGE[1], stem,
                f"Dmin[{c}]={p['Dmin'][c]} outside range")
            chk(nm.WB_RANGE[0] <= p["wb_low"][c] <= nm.WB_RANGE[1], stem,
                f"wb_low[{c}] outside range")
            chk(nm.WB_RANGE[0] <= p["wb_high"][c] <= nm.WB_RANGE[1], stem,
                f"wb_high[{c}] outside range")
        chk(all(math.isfinite(v) for v in p["Dmin"] + p["wb_low"] + p["wb_high"]),
            stem, "non-finite param component")

        # picker normalization: wb_low max == 1, wb_high min == 1
        chk(abs(max(p["wb_low"]) - 1.0) <= WB_NORM_EPS, stem,
            f"max(wb_low)={max(p['wb_low'])} != 1")
        chk(abs(min(p["wb_high"]) - 1.0) <= WB_NORM_EPS, stem,
            f"min(wb_high)={min(p['wb_high'])} != 1")

        # film base must stay orange
        chk(p["Dmin"][0] > p["Dmin"][1] > p["Dmin"][2], stem,
            f"Dmin not orange-ordered: {p['Dmin']}")

        # print curve: pipeline gamma (user taste), darktable-default soft_clip
        chk(p["gamma"] == an.PRINT_GAMMA and p["soft_clip"] == nm.SOFT_CLIP_DEFAULT,
            stem, "gamma/soft_clip not at pipeline defaults")

        # hex blob round-trip
        d = nm.decode_negadoctor_params(fr["params_hex"])
        chk(abs(d["exposure"] - p["exposure"]) < 1e-6
            and all(abs(a - b) < 1e-6 for a, b in zip(d["Dmin"], p["Dmin"])),
            stem, "params_hex does not round-trip to params")

        # patch rects inside frame bounds; shadows/highlights additionally
        # inside the content crop (the film-base rect may legitimately sit in
        # the rejected ring — base lives in gaps/rebate, and the crop governs
        # LEVEL computations, not the base search)
        w, h = fr["width"], fr["height"]
        l, t, r, b = fr["border"]
        for kind in ("base", "shadow_patch", "highlight_patch"):
            obj = fr.get(kind) if kind != "base" else fr.get("base")
            if not obj:
                continue
            x, y, ww, hh = obj["rect"]
            chk(0 <= x and 0 <= y and x + ww <= w and y + hh <= h, stem,
                f"{kind} rect {obj['rect']} out of bounds")
            if kind != "base":
                chk(x >= l and y >= t and x + ww <= w - r and y + hh <= h - b,
                    stem,
                    f"{kind} rect {obj['rect']} outside content crop {fr['border']}")

    # vignette: roll-level params sane and fit trustworthy
    vig_frames = [f for f in ok_frames if f.get("vignette")]
    if vig_frames:
        v = vig_frames[0]["vignette"]
        for name in ("strength", "radius", "steepness"):
            val = v.get(name)
            chk(val is not None and 0.0 <= val <= 1.0, "roll",
                f"vignette {name}={val} outside [0,1]")

    # exposure-ordering consistency: Dmin scales with the exposure factor
    cmp = [f for f in ok_frames if not f["exif"].get("missing_exif")]
    for i in range(len(cmp)):
        for j in range(i + 1, len(cmp)):
            fi, fj = cmp[i], cmp[j]
            fact_ratio = fi["exposure_factor"] / fj["exposure_factor"]
            for c in range(3):
                a, b_ = fi["params"]["Dmin"][c], fj["params"]["Dmin"][c]
                # skip channels saturated by the clamp
                if (a >= nm.DMIN_RANGE[1] - 1e-6 or b_ >= nm.DMIN_RANGE[1] - 1e-6):
                    continue
                ratio = a / b_
                if abs(ratio / fact_ratio - 1.0) > EXPOSURE_ORDER_REL_TOL:
                    bad.append(f"{fi['stem']}/{fj['stem']}: Dmin[{c}] ratio "
                               f"{ratio:.4f} vs exposure ratio {fact_ratio:.4f}")
    return bad


def selftest_invariants():
    """Test for the test: a deliberately broken frame must be flagged."""
    base = {
        "stem": "FAKE", "error": None, "width": 1000, "height": 660,
        "border": (10, 10, 10, 10),
        "exif": {"missing_exif": False}, "exposure_factor": 1.0,
        "base": {"rect": [100, 100, 40, 40]},
        "shadow_patch": None, "highlight_patch": None,
    }
    params = {
        "Dmin": [0.7, 0.3, 0.15], "wb_high": [1.2, 1.1, 1.0],
        "wb_low": [1.0, 0.9, 0.8], "D_max": 2.0, "offset": -0.05,
        "black": 0.1, "gamma": an.PRINT_GAMMA,
        "soft_clip": nm.SOFT_CLIP_DEFAULT, "exposure": 0.95, "film_stock": 1,
    }
    good = dict(base, params=params,
                params_hex=nm.encode_negadoctor_params(params))
    assert not check_frame_invariants([good], None), \
        "invariant self-test: clean frame was flagged"

    broken_params = dict(params, wb_low=[0.9, 0.8, 0.7],          # max != 1
                         Dmin=[0.15, 0.3, 0.7])                    # not orange
    broken = dict(base, params=broken_params,
                  params_hex=nm.encode_negadoctor_params(broken_params),
                  shadow_patch={"rect": [2, 2, 40, 40]})           # outside crop
    violations = check_frame_invariants([broken], None)
    assert len(violations) >= 3, \
        f"invariant self-test: broken frame produced only {violations}"
    print("Invariant checker self-test: OK")


# ---------------------------------------------------------------------------
# Baseline diff
# ---------------------------------------------------------------------------

def load_baseline(roll_id):
    """Baselines are per-roll (stems collide across rolls):
    baseline_session/<roll_id>/*_debug_nega.json."""
    d = BASELINE_DIR / roll_id
    if not d.is_dir():
        return {}
    out = {}
    for f in sorted(d.glob("*_debug_nega.json")):
        with open(f) as fh:
            data = json.load(fh)
        out[data["stem"]] = data
    return out


def rect_center(rect):
    return (rect[0] + rect[2] / 2.0, rect[1] + rect[3] / 2.0)


def diff_frame_vs_baseline(fr, base):
    """Return list of difference strings for one frame."""
    diffs = []
    p, bp = fr["params"], base["params"]

    for c in range(3):
        rel = abs(p["Dmin"][c] / max(bp["Dmin"][c], 1e-9) - 1.0)
        if rel > TOL_DMIN_REL:
            diffs.append(f"Dmin[{c}] {p['Dmin'][c]:.4f} vs {bp['Dmin'][c]:.4f}")
        if abs(p["wb_low"][c] - bp["wb_low"][c]) > TOL_WB:
            diffs.append(f"wb_low[{c}] {p['wb_low'][c]:.3f} vs {bp['wb_low'][c]:.3f}")
        if abs(p["wb_high"][c] - bp["wb_high"][c]) > TOL_WB:
            diffs.append(f"wb_high[{c}] {p['wb_high'][c]:.3f} vs {bp['wb_high'][c]:.3f}")
    if abs(p["D_max"] - bp["D_max"]) > TOL_DMAX:
        diffs.append(f"D_max {p['D_max']:.3f} vs {bp['D_max']:.3f}")
    if abs(p["black"] - bp["black"]) > TOL_BLACK:
        diffs.append(f"black {p['black']:.4f} vs {bp['black']:.4f}")
    if abs(p["exposure"] - bp["exposure"]) > TOL_EXPOSURE:
        diffs.append(f"exposure {p['exposure']:.4f} vs {bp['exposure']:.4f}")

    base_local = (base.get("film_base") or {}).get("local")
    ours_local = fr.get("base")
    if bool(base_local) != bool(ours_local):
        diffs.append(f"film-base candidate presence changed "
                     f"({bool(ours_local)} vs {bool(base_local)})")
    elif base_local and ours_local:
        bx, by = rect_center(base_local["rect"])
        ox, oy = rect_center(ours_local["rect"])
        d = math.hypot(ox - bx, oy - by)
        if d > TOL_PATCH_CENTER_PX:
            diffs.append(f"film-base moved {d:.0f}px "
                         f"({ours_local['rect']} vs {base_local['rect']})")

    # shadows / highlights patches: presence, position AND size (sizes are
    # user-tunable via the debug UI and must survive algorithm changes)
    base_patches = base.get("patches") or {}
    for kind, key in (("shadows", "shadow_patch"), ("highlights", "highlight_patch")):
        b_obj = base_patches.get(kind) or {}
        b_rect = b_obj.get("rect")
        o_obj = fr.get(key)
        o_rect = o_obj["rect"] if o_obj else None
        if bool(b_rect) != bool(o_rect):
            diffs.append(f"{kind} patch presence changed "
                         f"({bool(o_rect)} vs {bool(b_rect)})")
            continue
        if not b_rect:
            continue
        bx, by = rect_center(b_rect)
        ox, oy = rect_center(o_rect)
        d = math.hypot(ox - bx, oy - by)
        if d > TOL_PATCH_CENTER_PX:
            diffs.append(f"{kind} patch moved {d:.0f}px ({o_rect} vs {b_rect})")
        if (abs(o_rect[2] - b_rect[2]) > TOL_PATCH_SIZE_PX
                or abs(o_rect[3] - b_rect[3]) > TOL_PATCH_SIZE_PX):
            diffs.append(f"{kind} patch size changed "
                         f"{o_rect[2]}x{o_rect[3]} vs {b_rect[2]}x{b_rect[3]}")
    return diffs


def check_crop_containment(frames, fixtures):
    """HARD RULE (user, 2026-06-12): the detected content crop must NEVER
    extend outside the user's hand-drawn crop annotations — the user rects
    are ground truth and anything outside them is holder/junk that poisons
    the level analysis. Any violation FAILS the suite.

    Returns a list of violation strings."""
    violations = []
    by_stem = {fr["stem"]: fr for fr in frames}
    checked = 0
    for f in fixtures:
        data = json.loads(f.read_text())
        crop = data.get("crop_correction")
        if not crop or not crop.get("corrected"):
            continue
        stem = data.get("stem") or f.name.replace("_annotations.json", "")
        fr = by_stem.get(stem)
        if fr is None or fr.get("error") or "border" not in fr:
            continue
        checked += 1
        x, y, cw, ch = _rect_to_px(crop["corrected"], fr["width"], fr["height"])
        user = (x, y, fr["width"] - x - cw, fr["height"] - y - ch)
        det = fr["border"]
        # The user crops are stored as normalized fractions; denormalizing them
        # onto a frame of a different resolution than they were drawn at rounds
        # by up to 1px. Allow that slack so cross-resolution rounding is not a
        # spurious "crop extends outside" violation (real over-includes are
        # many px - DSC_0037's was 50).
        for i, edge in enumerate(("left", "top", "right", "bottom")):
            if det[i] < user[i] - CROP_CONTAINMENT_ROUND_TOL:
                violations.append(
                    f"{stem}: detected {edge} margin {det[i]} < user "
                    f"{user[i]} (crop extends outside the user rect) "
                    f"[{f.parent.name}]")
    print(f"  containment checked on {checked} crop fixture(s), "
          f"{len(violations)} violation(s)")
    return violations


def report_annotated_frames(frames, fixtures):
    """Informational check against committed user annotations
    (fixtures/rolls/<roll_id>/.../{stem}_annotations.json): show whether the
    detector now finds patches on frames the user had to correct, and how
    the wb from the user's rects compares to what was applied."""
    import auto_negadoctor as an
    import nega_model as nm
    if not fixtures:
        print("  (no annotation fixtures)")
        return
    by_stem = {fr["stem"]: fr for fr in frames}
    for f in fixtures:
        data = json.loads(f.read_text())
        stem = data.get("stem") or f.name.replace("_annotations.json", "")
        fr = by_stem.get(stem)
        if fr is None or fr.get("error") or "params" not in fr:
            print(f"  {stem} [{f.parent.name}]: not in current run")
            continue
        print(f"  {stem} [{f.parent.name}]:")
        try:
            lin = an.load_frame(fr["path"])[1]
        except Exception as e:
            print(f"    cannot load frame: {e}")
            continue
        p = fr["params"]
        for kind, entry in (data.get("patch_corrections") or {}).items():
            rect = entry.get("corrected")
            if not rect:
                continue
            x, y, w, h = _rect_to_px(rect, fr["width"], fr["height"])
            rgb = [float(v) for v in lin[y:y + h, x:x + w].reshape(-1, 3).mean(axis=0)]
            key = {"shadows": "shadow_patch", "highlights": "highlight_patch",
                   "film_base": "base"}.get(kind)
            found = bool(fr.get(key)) if key else False
            line = f"    {kind}: detector {'FOUND a patch' if found else 'fell back'}"
            try:
                if kind == "shadows":
                    wb = nm.compute_wb_low(p["Dmin"], rgb, p["D_max"])
                    line += (f"; user-rect wb_low ({', '.join(f'{v:.3f}' for v in wb)})"
                             f" vs applied ({', '.join(f'{v:.3f}' for v in p['wb_low'])})")
                elif kind == "highlights":
                    wb = nm.compute_wb_high(p["Dmin"], rgb, p["D_max"],
                                            p["offset"], p["wb_low"])
                    line += (f"; user-rect wb_high ({', '.join(f'{v:.3f}' for v in wb)})"
                             f" vs applied ({', '.join(f'{v:.3f}' for v in p['wb_high'])})")
            except (ValueError, ZeroDivisionError, OverflowError):
                line += "; user-rect wb DEGENERATE (patch too close to film base)"
            print(line)
        for kind, entry in (data.get("wb_overrides") or {}).items():
            chosen = entry.get("corrected")
            applied = p.get("wb_low" if kind == "shadows" else "wb_high")
            if chosen and applied:
                print(f"    wb {kind} (wheel-picked): user "
                      f"({', '.join(f'{v:.3f}' for v in chosen)}) vs applied "
                      f"({', '.join(f'{v:.3f}' for v in applied)})  "
                      "<- tuning target")
            else:
                print(f"    wb {kind} (wheel-picked): user {chosen}")
        for name, entry in (data.get("print_overrides") or {}).items():
            applied = p.get(name)
            corrected = entry.get("corrected")
            if applied is not None and corrected is not None:
                print(f"    print {name}: user {corrected:.4f} vs applied "
                      f"{applied:.4f} ({corrected - applied:+.4f})")
            else:
                print(f"    print {name}: user {corrected}")
        crop = data.get("crop_correction")
        if crop and crop.get("corrected"):
            l, t, r, b = fr.get("border") or (0, 0, 0, 0)
            auto_rect = [l, t, fr["width"] - l - r, fr["height"] - t - b]
            user_rect = _rect_to_px(crop["corrected"], fr["width"], fr["height"])
            print(f"    crop: user {user_rect} vs auto border "
                  f"rect {auto_rect} (holder detection tuning signal)")


def _load_ground_truth(fixtures):
    """Per-stem, field-level last-writer-wins map of the user's hand-tuned
    target params, gathered from one roll's annotation sessions. Wheel-picked
    `wb_overrides` -> wb_low/wb_high; `print_overrides` -> black/exposure/gamma.
    Later dated sessions (e.g. 2026-06-13_wb_print_roll) override earlier ones
    (e.g. 2026-06-11_taste) for the same stem+field. Returns {stem: gt}."""
    gt_by_stem = {}
    for f in fixtures:
        data = json.loads(f.read_text())
        stem = data.get("stem") or f.name.replace("_annotations.json", "")
        gt = gt_by_stem.setdefault(stem, {})
        touched = False
        for kind, key in (("shadows", "wb_low"), ("highlights", "wb_high")):
            entry = (data.get("wb_overrides") or {}).get(kind) or {}
            corrected = entry.get("corrected")
            if corrected:
                gt[key] = [float(v) for v in corrected]
                touched = True
        for name in ("black", "exposure", "gamma"):
            entry = (data.get("print_overrides") or {}).get(name) or {}
            corrected = entry.get("corrected")
            if corrected is not None:
                gt[name] = float(corrected)
                touched = True
        if touched:
            gt["session"] = f.parent.name
    return {s: gt for s, gt in gt_by_stem.items() if gt}


def _ground_truth_violations(stem, params, gt):
    """Compare current algorithm params against one stem's ground truth.
    Returns (violations, deltas): a list of strings and a {param: abs_delta}
    dict (per wb component keyed e.g. 'wb_low[1]'). Pure — no I/O."""
    violations, deltas = [], {}
    session = gt.get("session", "?")

    def note(label, applied, target, tol):
        d = abs(applied - target)
        deltas[label] = d
        if d > tol:
            violations.append(
                f"{stem}: {label} target {target:.4f} vs applied "
                f"{applied:.4f} (Δ{d:.4f} > {tol}) [{session}]")

    for key in ("wb_low", "wb_high"):
        target = gt.get(key)
        applied = params.get(key)
        if target and applied:
            for c in range(3):
                note(f"{key}[{c}]", applied[c], target[c], TOL_GT_WB)
    for name, tol in (("black", TOL_GT_BLACK),
                      ("exposure", TOL_GT_EXPOSURE),
                      ("gamma", TOL_GT_GAMMA)):
        target = gt.get(name)
        applied = params.get(name)
        if target is not None and applied is not None:
            note(name, applied, target, tol)
    return violations, deltas


def check_ground_truth(frames, fixtures):
    """HARD gate: the production params must match the user's hand-tuned
    wheel/print annotations (the ground truth this feature must converge to).
    Strict tolerances; expected to FAIL until the algorithm is tuned. Returns
    a list of violation strings and prints a per-param aggregate summary."""
    gt_by_stem = _load_ground_truth(fixtures)
    if not gt_by_stem:
        print("  (no wb/print ground-truth annotations)")
        return []
    by_stem = {fr["stem"]: fr for fr in frames}
    violations = []
    all_deltas = {}   # label -> [abs deltas across frames]
    checked = 0
    for stem, gt in sorted(gt_by_stem.items()):
        fr = by_stem.get(stem)
        if fr is None or fr.get("error") or "params" not in fr:
            continue
        checked += 1
        vios, deltas = _ground_truth_violations(stem, fr["params"], gt)
        violations.extend(vios)
        for label, d in deltas.items():
            all_deltas.setdefault(label, []).append(d)

    # aggregate dashboard: group per-component wb into wb_low/wb_high
    def group(label):
        return label.split("[")[0]
    grouped = {}
    for label, ds in all_deltas.items():
        grouped.setdefault(group(label), []).extend(ds)
    print(f"  checked {checked} frame(s) against ground truth, "
          f"{len(violations)} violation(s)")
    if grouped:
        print("  aggregate abs delta (algorithm vs ground truth):")
        for name in ("wb_low", "wb_high", "black", "exposure", "gamma"):
            ds = grouped.get(name)
            if not ds:
                continue
            ds_sorted = sorted(ds)
            median = ds_sorted[len(ds_sorted) // 2]
            print(f"    {name:9s} median {median:.4f}  max {max(ds):.4f}  "
                  f"(n={len(ds)})")
    return violations


def selftest_ground_truth():
    """Test for the test: clean params pass, off params are flagged per param."""
    gt = {"wb_low": [1.0, 0.9, 0.8], "wb_high": [1.2, 1.1, 1.0],
          "black": 0.05, "exposure": 1.1, "gamma": 6.9, "session": "selftest"}
    clean = {"wb_low": [1.0, 0.9, 0.8], "wb_high": [1.2, 1.1, 1.0],
             "black": 0.05, "exposure": 1.1, "gamma": 6.9}
    vios, _ = _ground_truth_violations("CLEAN", clean, gt)
    assert not vios, f"ground-truth self-test: clean params flagged {vios}"

    off = {"wb_low": [1.0, 0.5, 0.8], "wb_high": [1.2, 1.1, 1.0],
           "black": 0.5, "exposure": 1.5, "gamma": 6.0}
    vios, _ = _ground_truth_violations("OFF", off, gt)
    # wb_low[1], black, exposure, gamma all exceed tolerance
    assert len(vios) >= 4, f"ground-truth self-test: off params under-flagged {vios}"
    print("Ground-truth checker self-test: OK")


# AI-variant gate (spec 03): scene_tuner nudges the analytical params toward the
# user's per-scene aesthetic. The strict per-frame GT match (check_ground_truth)
# stays RED by design (irreducible taste); this gate instead requires the AI
# variant to be no WORSE than analytical on any param's aggregate median delta
# (a regression guard for the scene_tuner calibration) and to stay clip-safe.
AI_GT_REGRESS_EPS = 0.01   # per-param median delta the AI variant may grow by


def _load_scene_labels(roll):
    """Committed LLM scene labels for this roll (its own scene_labels.json) so
    the AI-variant gate runs offline without Ollama. Living inside the roll
    folder, it is inherently roll-matched. Returns {stem: label} or {}."""
    path = roll["dir"] / "scene_labels.json"
    if not path.is_file():
        return {}
    return json.loads(path.read_text()).get("labels", {})


def check_ai_variant(frames, fixtures, roll):
    """HARD gate for the spec-03 AI variant: build it with scene_tuner from the
    committed scene labels and compare its ground-truth deltas to analytical.
    FAILs only if the AI variant REGRESSES a param's aggregate median delta
    (beyond AI_GT_REGRESS_EPS) or clips beyond CLIP_MAX_FRAC — i.e. it guards
    that the scene tuning is a net improvement, while the strict per-frame match
    remains the (red-by-design) check_ground_truth gate. Returns violations."""
    import numpy as np
    labels = _load_scene_labels(roll)
    gt_by_stem = _load_ground_truth(fixtures)
    if not labels or not gt_by_stem:
        print("  (no committed scene labels / ground truth - AI gate skipped)")
        return []
    try:
        import scene_tuner as st
    except Exception as e:
        print(f"  (scene_tuner unavailable: {e})")
        return []
    by_stem = {fr["stem"]: fr for fr in frames}
    fields = [("wb_low", TOL_GT_WB), ("wb_high", TOL_GT_WB),
              ("black", TOL_GT_BLACK), ("exposure", TOL_GT_EXPOSURE),
              ("gamma", TOL_GT_GAMMA)]
    agg = {f: {"ana": [], "ai": []} for f, _ in fields}
    vio_ana = vio_ai = checked = 0
    worst_clip = 0.0
    for stem, gt in sorted(gt_by_stem.items()):
        fr = by_stem.get(stem)
        if fr is None or fr.get("error") or "params" not in fr or not fr.get("border"):
            continue
        scene = st._validate(labels[stem]) if labels.get(stem) else None
        try:
            enc_f, lin = an.load_frame(fr["path"], fr.get("vignette"))
        except Exception:
            continue
        ai, _ = st.apply_scene_tuning(fr["params"], scene, lin, fr["border"])
        checked += 1
        vio_ana += len(_ground_truth_violations(stem, fr["params"], gt)[0])
        vio_ai += len(_ground_truth_violations(stem, ai, gt)[0])
        l, t, r, b = fr["border"]
        h, w = lin.shape[:2]
        s = max(1, int(round(w * an.PRINT_TUNE_SUBSAMPLE_FRAC)))
        region = lin[t:h - b:s, l:w - r:s].reshape(-1, 3)
        if region.size:
            out = nm.render_negadoctor(region, ai)
            worst_clip = max(worst_clip,
                             float(np.mean((out >= CLIP_OUT_THR).any(axis=1))))
        for f, _tol in fields:
            tgt = gt.get(f)
            if tgt is None:
                continue
            if isinstance(tgt, list):
                agg[f]["ana"] += [abs(fr["params"][f][c] - tgt[c]) for c in range(3)]
                agg[f]["ai"] += [abs(ai[f][c] - tgt[c]) for c in range(3)]
            else:
                agg[f]["ana"].append(abs(fr["params"][f] - tgt))
                agg[f]["ai"].append(abs(ai[f] - tgt))

    def med(v):
        return sorted(v)[len(v) // 2] if v else float("nan")

    violations = []
    print(f"  checked {checked} frame(s); strict GT violations: analytical "
          f"{vio_ana} -> AI {vio_ai}")
    print(f"  AI variant worst hard-clip {worst_clip:.2%} "
          f"(limit {CLIP_MAX_FRAC:.0%})")
    print("  aggregate abs delta vs GT (analytical -> AI; AI must not regress):")
    for f, tol in fields:
        a, i = agg[f]["ana"], agg[f]["ai"]
        if not a:
            continue
        ma, mi = med(a), med(i)
        tag = ("better" if mi < ma - 1e-9
               else "worse" if mi > ma + 1e-9 else "same")
        print(f"    {f:9s} {ma:.4f} -> {mi:.4f}  ({tag}, tol {tol}, n={len(a)})")
        if mi > ma + AI_GT_REGRESS_EPS:
            violations.append(
                f"AI variant regressed {f}: median {ma:.4f} -> {mi:.4f}")
    if worst_clip > CLIP_MAX_FRAC:
        violations.append(
            f"AI variant hard-clip {worst_clip:.2%} > {CLIP_MAX_FRAC:.0%}")
    return violations


def check_no_clipping(frames):
    """HARD gate the param ground-truth gate does NOT cover: render each frame's
    PRODUCTION params and flag any whose hard-clip fraction (pixels with any
    channel >= CLIP_OUT_THR) exceeds CLIP_MAX_FRAC. Subsamples for speed, using
    the same stride the print tuner uses. Returns a list of violation strings."""
    import numpy as np
    violations, worst = [], []
    for fr in frames:
        if fr.get("error") or "params" not in fr or not fr.get("border"):
            continue
        try:
            enc_f, lin = an.load_frame(fr["path"], fr.get("vignette"))
        except Exception:
            continue
        l, t, r, b = fr["border"]
        h, w = lin.shape[:2]
        s = max(1, int(round(w * an.PRINT_TUNE_SUBSAMPLE_FRAC)))
        region = lin[t:h - b:s, l:w - r:s].reshape(-1, 3)
        if region.size == 0:
            continue
        out = nm.render_negadoctor(region, fr["params"])
        clip = float(np.mean((out >= CLIP_OUT_THR).any(axis=1)))
        worst.append((fr["stem"], clip))
        if clip > CLIP_MAX_FRAC:
            violations.append(f"{fr['stem']}: hard-clip fraction {clip:.1%} "
                              f"> {CLIP_MAX_FRAC:.0%} (overexposed / unusable)")
    worst.sort(key=lambda x: -x[1])
    if worst:
        print("  checked {} frame(s); worst clip: {}".format(
            len(worst), ", ".join(f"{s} {c:.2%}" for s, c in worst[:3])))
    return violations


def run_roll(roll_info):
    """Run the full check suite for ONE roll. Returns (fail, warn)."""
    images, exif, fixtures = (roll_info["images"], roll_info["exif"],
                              roll_info["fixtures"])

    print(f"Running pipeline on {len(images)} test frame(s) "
          f"({Path(images[0]).suffix})...")
    frames, roll = an.process_roll(images, exif)
    errors = [f for f in frames if f.get("error")]
    for fr in errors:
        print(f"  ERR {fr['stem']}: {fr['error']}")

    if roll and roll.get("vignette"):
        v, vi = roll["vignette"], roll.get("vignette_info") or {}
        print(f"Vignette: strength={v['strength']:.3f} radius={v['radius']:.3f} "
              f"steepness={v['steepness']:.3f} "
              f"(corner falloff {vi.get('corner_falloff', 0):.1%}, "
              f"residual {vi.get('residual')})")

    print()
    print("--- Invariants ---")
    violations = check_frame_invariants(frames, roll)
    if violations:
        for v in violations:
            print(f"  VIOLATION: {v}")
    else:
        print("  all invariants hold")

    print()
    print("--- Crop containment (HARD rule: never outside user crops) ---")
    containment = check_crop_containment(frames, fixtures)
    for v in containment:
        print(f"  VIOLATION: {v}")

    print()
    print("--- Annotated frames (user corrections; informational) ---")
    report_annotated_frames(frames, fixtures)

    print()
    print("--- Ground truth (HARD gate: algorithm must match user's "
          "wheel/print annotations) ---")
    ground_truth = check_ground_truth(frames, fixtures)
    for v in ground_truth:
        print(f"  VIOLATION: {v}")

    print()
    print("--- AI variant (HARD gate: scene_tuner must improve, not regress, "
          "vs analytical) ---")
    ai_variant = check_ai_variant(frames, fixtures, roll_info)
    for v in ai_variant:
        print(f"  VIOLATION: {v}")
    if not ai_variant:
        print("  AI variant improves/holds every param and is clip-safe")

    print()
    print("--- No clipping (HARD gate: production render must not blow out "
          "highlights) ---")
    clipping = check_no_clipping(frames)
    for v in clipping:
        print(f"  VIOLATION: {v}")
    if not clipping:
        print("  no frame exceeds the hard-clip limit")

    print()
    print("--- Baseline diff ---")
    baseline = load_baseline(roll_info["id"])
    diff_frames = 0
    compared = 0
    winner_changed = False
    if not baseline:
        print(f"  no baseline_session/{roll_info['id']}/ yet - run "
              "generate_baseline.py after a")
        print("  user-approved debug-UI review to enable regression diffs")
    else:
        base_winner = next((b["film_base"]["global_winner_stem"]
                            for b in baseline.values()
                            if b.get("film_base")), None)
        if roll and base_winner and roll["winner_stem"] != base_winner:
            winner_changed = True
            print(f"  GLOBAL WINNER CHANGED: {roll['winner_stem']} vs {base_winner}")
        for fr in frames:
            if fr.get("error") or fr["stem"] not in baseline:
                continue
            compared += 1
            diffs = diff_frame_vs_baseline(fr, baseline[fr["stem"]])
            if diffs:
                diff_frames += 1
                print(f"  {fr['stem']}:")
                for d in diffs:
                    print(f"    {d}")
        print(f"  {diff_frames}/{compared} frame(s) differ from baseline")

    print()
    fail = (bool(violations) or bool(errors) or bool(containment)
            or bool(ground_truth) or bool(clipping) or bool(ai_variant))
    warn = False
    if compared:
        frac = diff_frames / compared
        if winner_changed or frac > WARN_DIFF_FRAC:
            fail = True
        elif frac > PASS_DIFF_FRAC:
            warn = True

    verdict = "FAIL" if fail else ("WARN" if warn else "PASS")
    print(f"ROLL {roll_info['id']} VERDICT: {verdict}")
    return fail, warn


def main():
    selftest_invariants()
    selftest_ground_truth()

    rolls = discover_rolls()
    if not rolls:
        # The heavy TIFF exports are NOT committed (see fixtures/rolls/README).
        # Repopulate them with a fresh darktable export, then re-run.
        print("SKIP: no annotated rolls with local TIFFs under", ROLLS_DIR)
        print("  Each roll lives in fixtures/rolls/<roll_id>/ with its committed")
        print("  annotations; its linear-Rec2020 TIFF exports + exif_params.txt")
        print("  are gitignored. Export the roll from darktable (AutoNegadoctor")
        print("  in-place, keep temp folder) and copy the *.tif files +")
        print("  exif_params.txt into the roll's folder. Detection is")
        print("  resolution-independent, so any export width works.")
        return 0

    print(f"Discovered {len(rolls)} annotated roll(s) with local TIFFs: "
          f"{', '.join(r['id'] for r in rolls)}")
    any_fail = any_warn = False
    for roll_info in rolls:
        print()
        print("=" * 70)
        print(f"ROLL {roll_info['id']}  ({len(roll_info['images'])} frame(s), "
              f"{len(roll_info['fixtures'])} annotation file(s))")
        print("=" * 70)
        fail, warn = run_roll(roll_info)
        any_fail = any_fail or fail
        any_warn = any_warn or warn

    print()
    verdict = "FAIL" if any_fail else ("WARN" if any_warn else "PASS")
    print(f"OVERALL VERDICT ({len(rolls)} roll(s)): {verdict}")
    return 1 if any_fail else 0


if __name__ == "__main__":
    sys.exit(main())
