"""Quality / regression suite for auto_negadoctor.

Two layers:
  1. Baseline-independent INVARIANTS over a fresh pipeline run on
     tests/images (param ranges, wb normalization, exposure-ordering
     consistency of Dmin across frames, patches inside frame bounds and
     outside the holder border, hex round-trip).
  2. Baseline diff vs tests/baseline_session/{stem}_debug_nega.json
     (generated by generate_baseline.py after user approval): global winner
     identity, film-base location, params within tolerances.

Run: conda run -n autocrop python auto_negadoctor/tests/run_quality_tests.py
Exit code: 0 = PASS or WARN, 1 = FAIL.
"""

import json
import math
import os
import sys
from pathlib import Path

TESTS_DIR = Path(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, str(TESTS_DIR.parent))
import auto_negadoctor as an
import nega_model as nm

IMAGES_DIR = TESTS_DIR / "images"            # sRGB JPEG fallback fixtures
IMAGES_TIF_DIR = TESTS_DIR / "images_tif"    # real linear-Rec2020 TIFF exports
ANNOTATIONS_DIR = TESTS_DIR / "fixtures" / "annotations"
BASELINE_DIR = TESTS_DIR / "baseline_session"


def list_test_images():
    """Prefer the TIFF fixtures (real export format) over the JPEGs.
    Returns (paths, exif_by_stem)."""
    tifs = sorted(IMAGES_TIF_DIR.glob("*.tif"))
    if tifs:
        import auto_negadoctor as _an
        exif = _an.parse_exif_params(str(IMAGES_TIF_DIR / "exif_params.txt"))
        return [str(p) for p in tifs], exif
    return [str(p) for p in sorted(IMAGES_DIR.glob("*.jpg"))], {}

# Baseline diff tolerances (deterministic pipeline; slack covers const tweaks)
TOL_DMIN_REL = 0.10
TOL_DMAX = 0.20
TOL_WB = 0.10
TOL_BLACK = 0.05
TOL_EXPOSURE = 0.05
TOL_PATCH_CENTER_PX = 30.0
TOL_PATCH_SIZE_PX = 10
# Verdict gates: fraction of frames allowed to differ from baseline
PASS_DIFF_FRAC = 0.10
WARN_DIFF_FRAC = 0.30

WB_NORM_EPS = 1e-3
EXPOSURE_ORDER_REL_TOL = 0.02   # Dmin_i/Dmin_j vs factor_i/factor_j


# ---------------------------------------------------------------------------
# Invariants (baseline-independent)
# ---------------------------------------------------------------------------

def check_frame_invariants(frames, roll):
    """Return a list of violation strings (empty = all good)."""
    bad = []

    def chk(cond, stem, msg):
        if not cond:
            bad.append(f"{stem}: {msg}")

    ok_frames = [f for f in frames if not f.get("error") and f.get("params")]
    for fr in ok_frames:
        stem = fr["stem"]
        p = fr["params"]

        for name, val, rng in (
            ("D_max", p["D_max"], nm.DMAX_RANGE),
            ("offset", p["offset"], nm.OFFSET_RANGE),
            ("black", p["black"], nm.BLACK_RANGE),
            ("exposure", p["exposure"], nm.EXPOSURE_RANGE),
        ):
            chk(math.isfinite(val) and rng[0] <= val <= rng[1], stem,
                f"{name}={val} outside {rng}")
        for c in range(3):
            chk(nm.DMIN_RANGE[0] <= p["Dmin"][c] <= nm.DMIN_RANGE[1], stem,
                f"Dmin[{c}]={p['Dmin'][c]} outside range")
            chk(nm.WB_RANGE[0] <= p["wb_low"][c] <= nm.WB_RANGE[1], stem,
                f"wb_low[{c}] outside range")
            chk(nm.WB_RANGE[0] <= p["wb_high"][c] <= nm.WB_RANGE[1], stem,
                f"wb_high[{c}] outside range")
        chk(all(math.isfinite(v) for v in p["Dmin"] + p["wb_low"] + p["wb_high"]),
            stem, "non-finite param component")

        # picker normalization: wb_low max == 1, wb_high min == 1
        chk(abs(max(p["wb_low"]) - 1.0) <= WB_NORM_EPS, stem,
            f"max(wb_low)={max(p['wb_low'])} != 1")
        chk(abs(min(p["wb_high"]) - 1.0) <= WB_NORM_EPS, stem,
            f"min(wb_high)={min(p['wb_high'])} != 1")

        # film base must stay orange
        chk(p["Dmin"][0] > p["Dmin"][1] > p["Dmin"][2], stem,
            f"Dmin not orange-ordered: {p['Dmin']}")

        # print curve: pipeline gamma (user taste), darktable-default soft_clip
        chk(p["gamma"] == an.PRINT_GAMMA and p["soft_clip"] == nm.SOFT_CLIP_DEFAULT,
            stem, "gamma/soft_clip not at pipeline defaults")

        # hex blob round-trip
        d = nm.decode_negadoctor_params(fr["params_hex"])
        chk(abs(d["exposure"] - p["exposure"]) < 1e-6
            and all(abs(a - b) < 1e-6 for a, b in zip(d["Dmin"], p["Dmin"])),
            stem, "params_hex does not round-trip to params")

        # patch rects inside frame bounds; shadows/highlights additionally
        # inside the content crop (the film-base rect may legitimately sit in
        # the rejected ring — base lives in gaps/rebate, and the crop governs
        # LEVEL computations, not the base search)
        w, h = fr["width"], fr["height"]
        l, t, r, b = fr["border"]
        for kind in ("base", "shadow_patch", "highlight_patch"):
            obj = fr.get(kind) if kind != "base" else fr.get("base")
            if not obj:
                continue
            x, y, ww, hh = obj["rect"]
            chk(0 <= x and 0 <= y and x + ww <= w and y + hh <= h, stem,
                f"{kind} rect {obj['rect']} out of bounds")
            if kind != "base":
                chk(x >= l and y >= t and x + ww <= w - r and y + hh <= h - b,
                    stem,
                    f"{kind} rect {obj['rect']} outside content crop {fr['border']}")

    # vignette: roll-level params sane and fit trustworthy
    vig_frames = [f for f in ok_frames if f.get("vignette")]
    if vig_frames:
        v = vig_frames[0]["vignette"]
        for name in ("strength", "radius", "steepness"):
            val = v.get(name)
            chk(val is not None and 0.0 <= val <= 1.0, "roll",
                f"vignette {name}={val} outside [0,1]")

    # exposure-ordering consistency: Dmin scales with the exposure factor
    cmp = [f for f in ok_frames if not f["exif"].get("missing_exif")]
    for i in range(len(cmp)):
        for j in range(i + 1, len(cmp)):
            fi, fj = cmp[i], cmp[j]
            fact_ratio = fi["exposure_factor"] / fj["exposure_factor"]
            for c in range(3):
                a, b_ = fi["params"]["Dmin"][c], fj["params"]["Dmin"][c]
                # skip channels saturated by the clamp
                if (a >= nm.DMIN_RANGE[1] - 1e-6 or b_ >= nm.DMIN_RANGE[1] - 1e-6):
                    continue
                ratio = a / b_
                if abs(ratio / fact_ratio - 1.0) > EXPOSURE_ORDER_REL_TOL:
                    bad.append(f"{fi['stem']}/{fj['stem']}: Dmin[{c}] ratio "
                               f"{ratio:.4f} vs exposure ratio {fact_ratio:.4f}")
    return bad


def selftest_invariants():
    """Test for the test: a deliberately broken frame must be flagged."""
    base = {
        "stem": "FAKE", "error": None, "width": 1000, "height": 660,
        "border": (10, 10, 10, 10),
        "exif": {"missing_exif": False}, "exposure_factor": 1.0,
        "base": {"rect": [100, 100, 40, 40]},
        "shadow_patch": None, "highlight_patch": None,
    }
    params = {
        "Dmin": [0.7, 0.3, 0.15], "wb_high": [1.2, 1.1, 1.0],
        "wb_low": [1.0, 0.9, 0.8], "D_max": 2.0, "offset": -0.05,
        "black": 0.1, "gamma": an.PRINT_GAMMA,
        "soft_clip": nm.SOFT_CLIP_DEFAULT, "exposure": 0.95, "film_stock": 1,
    }
    good = dict(base, params=params,
                params_hex=nm.encode_negadoctor_params(params))
    assert not check_frame_invariants([good], None), \
        "invariant self-test: clean frame was flagged"

    broken_params = dict(params, wb_low=[0.9, 0.8, 0.7],          # max != 1
                         Dmin=[0.15, 0.3, 0.7])                    # not orange
    broken = dict(base, params=broken_params,
                  params_hex=nm.encode_negadoctor_params(broken_params),
                  shadow_patch={"rect": [2, 2, 40, 40]})           # outside crop
    violations = check_frame_invariants([broken], None)
    assert len(violations) >= 3, \
        f"invariant self-test: broken frame produced only {violations}"
    print("Invariant checker self-test: OK")


# ---------------------------------------------------------------------------
# Baseline diff
# ---------------------------------------------------------------------------

def load_baseline():
    if not BASELINE_DIR.is_dir():
        return {}
    out = {}
    for f in sorted(BASELINE_DIR.glob("*_debug_nega.json")):
        with open(f) as fh:
            data = json.load(fh)
        out[data["stem"]] = data
    return out


def rect_center(rect):
    return (rect[0] + rect[2] / 2.0, rect[1] + rect[3] / 2.0)


def diff_frame_vs_baseline(fr, base):
    """Return list of difference strings for one frame."""
    diffs = []
    p, bp = fr["params"], base["params"]

    for c in range(3):
        rel = abs(p["Dmin"][c] / max(bp["Dmin"][c], 1e-9) - 1.0)
        if rel > TOL_DMIN_REL:
            diffs.append(f"Dmin[{c}] {p['Dmin'][c]:.4f} vs {bp['Dmin'][c]:.4f}")
        if abs(p["wb_low"][c] - bp["wb_low"][c]) > TOL_WB:
            diffs.append(f"wb_low[{c}] {p['wb_low'][c]:.3f} vs {bp['wb_low'][c]:.3f}")
        if abs(p["wb_high"][c] - bp["wb_high"][c]) > TOL_WB:
            diffs.append(f"wb_high[{c}] {p['wb_high'][c]:.3f} vs {bp['wb_high'][c]:.3f}")
    if abs(p["D_max"] - bp["D_max"]) > TOL_DMAX:
        diffs.append(f"D_max {p['D_max']:.3f} vs {bp['D_max']:.3f}")
    if abs(p["black"] - bp["black"]) > TOL_BLACK:
        diffs.append(f"black {p['black']:.4f} vs {bp['black']:.4f}")
    if abs(p["exposure"] - bp["exposure"]) > TOL_EXPOSURE:
        diffs.append(f"exposure {p['exposure']:.4f} vs {bp['exposure']:.4f}")

    base_local = (base.get("film_base") or {}).get("local")
    ours_local = fr.get("base")
    if bool(base_local) != bool(ours_local):
        diffs.append(f"film-base candidate presence changed "
                     f"({bool(ours_local)} vs {bool(base_local)})")
    elif base_local and ours_local:
        bx, by = rect_center(base_local["rect"])
        ox, oy = rect_center(ours_local["rect"])
        d = math.hypot(ox - bx, oy - by)
        if d > TOL_PATCH_CENTER_PX:
            diffs.append(f"film-base moved {d:.0f}px "
                         f"({ours_local['rect']} vs {base_local['rect']})")

    # shadows / highlights patches: presence, position AND size (sizes are
    # user-tunable via the debug UI and must survive algorithm changes)
    base_patches = base.get("patches") or {}
    for kind, key in (("shadows", "shadow_patch"), ("highlights", "highlight_patch")):
        b_obj = base_patches.get(kind) or {}
        b_rect = b_obj.get("rect")
        o_obj = fr.get(key)
        o_rect = o_obj["rect"] if o_obj else None
        if bool(b_rect) != bool(o_rect):
            diffs.append(f"{kind} patch presence changed "
                         f"({bool(o_rect)} vs {bool(b_rect)})")
            continue
        if not b_rect:
            continue
        bx, by = rect_center(b_rect)
        ox, oy = rect_center(o_rect)
        d = math.hypot(ox - bx, oy - by)
        if d > TOL_PATCH_CENTER_PX:
            diffs.append(f"{kind} patch moved {d:.0f}px ({o_rect} vs {b_rect})")
        if (abs(o_rect[2] - b_rect[2]) > TOL_PATCH_SIZE_PX
                or abs(o_rect[3] - b_rect[3]) > TOL_PATCH_SIZE_PX):
            diffs.append(f"{kind} patch size changed "
                         f"{o_rect[2]}x{o_rect[3]} vs {b_rect[2]}x{b_rect[3]}")
    return diffs


def check_crop_containment(frames):
    """HARD RULE (user, 2026-06-12): the detected content crop must NEVER
    extend outside the user's hand-drawn crop annotations — the user rects
    are ground truth and anything outside them is holder/junk that poisons
    the level analysis. Any violation FAILS the suite.

    Returns a list of violation strings."""
    violations = []
    fixtures = sorted(ANNOTATIONS_DIR.rglob("*_annotations.json")) \
        if ANNOTATIONS_DIR.is_dir() else []
    by_stem = {fr["stem"]: fr for fr in frames}
    checked = 0
    for f in fixtures:
        data = json.loads(f.read_text())
        crop = data.get("crop_correction")
        if not crop or not crop.get("corrected"):
            continue
        stem = data.get("stem") or f.name.replace("_annotations.json", "")
        fr = by_stem.get(stem)
        if fr is None or fr.get("error") or "border" not in fr:
            continue
        checked += 1
        x, y, cw, ch = crop["corrected"]
        user = (x, y, fr["width"] - x - cw, fr["height"] - y - ch)
        det = fr["border"]
        for i, edge in enumerate(("left", "top", "right", "bottom")):
            if det[i] < user[i]:
                violations.append(
                    f"{stem}: detected {edge} margin {det[i]} < user "
                    f"{user[i]} (crop extends outside the user rect) "
                    f"[{f.parent.name}]")
    print(f"  containment checked on {checked} crop fixture(s), "
          f"{len(violations)} violation(s)")
    return violations


def report_annotated_frames(frames):
    """Informational check against committed user annotations
    (tests/fixtures/annotations/{stem}_annotations.json): show whether the
    detector now finds patches on frames the user had to correct, and how
    the wb from the user's rects compares to what was applied."""
    import auto_negadoctor as an
    import nega_model as nm
    # annotation sessions live in dated subfolders (multiple per stem)
    fixtures = sorted(ANNOTATIONS_DIR.rglob("*_annotations.json")) \
        if ANNOTATIONS_DIR.is_dir() else []
    if not fixtures:
        print("  (no annotation fixtures)")
        return
    by_stem = {fr["stem"]: fr for fr in frames}
    for f in fixtures:
        data = json.loads(f.read_text())
        stem = data.get("stem") or f.name.replace("_annotations.json", "")
        fr = by_stem.get(stem)
        if fr is None or fr.get("error") or "params" not in fr:
            print(f"  {stem} [{f.parent.name}]: not in current run")
            continue
        print(f"  {stem} [{f.parent.name}]:")
        try:
            lin = an.load_frame(fr["path"])[1]
        except Exception as e:
            print(f"    cannot load frame: {e}")
            continue
        p = fr["params"]
        for kind, entry in (data.get("patch_corrections") or {}).items():
            rect = entry.get("corrected")
            if not rect:
                continue
            x, y, w, h = [int(v) for v in rect]
            rgb = [float(v) for v in lin[y:y + h, x:x + w].reshape(-1, 3).mean(axis=0)]
            key = {"shadows": "shadow_patch", "highlights": "highlight_patch",
                   "film_base": "base"}.get(kind)
            found = bool(fr.get(key)) if key else False
            line = f"    {kind}: detector {'FOUND a patch' if found else 'fell back'}"
            try:
                if kind == "shadows":
                    wb = nm.compute_wb_low(p["Dmin"], rgb, p["D_max"])
                    line += (f"; user-rect wb_low ({', '.join(f'{v:.3f}' for v in wb)})"
                             f" vs applied ({', '.join(f'{v:.3f}' for v in p['wb_low'])})")
                elif kind == "highlights":
                    wb = nm.compute_wb_high(p["Dmin"], rgb, p["D_max"],
                                            p["offset"], p["wb_low"])
                    line += (f"; user-rect wb_high ({', '.join(f'{v:.3f}' for v in wb)})"
                             f" vs applied ({', '.join(f'{v:.3f}' for v in p['wb_high'])})")
            except (ValueError, ZeroDivisionError, OverflowError):
                line += "; user-rect wb DEGENERATE (patch too close to film base)"
            print(line)
        for name, entry in (data.get("print_overrides") or {}).items():
            applied = p.get(name)
            corrected = entry.get("corrected")
            if applied is not None and corrected is not None:
                print(f"    print {name}: user {corrected:.4f} vs applied "
                      f"{applied:.4f} ({corrected - applied:+.4f})")
            else:
                print(f"    print {name}: user {corrected}")
        crop = data.get("crop_correction")
        if crop:
            l, t, r, b = fr.get("border") or (0, 0, 0, 0)
            auto_rect = [l, t, fr["width"] - l - r, fr["height"] - t - b]
            print(f"    crop: user {crop.get('corrected')} vs auto border "
                  f"rect {auto_rect} (holder detection tuning signal)")


def main():
    images, exif = list_test_images()
    if not images:
        print("FAIL: no test images in", IMAGES_TIF_DIR, "or", IMAGES_DIR)
        return 1

    selftest_invariants()

    print(f"Running pipeline on {len(images)} test frame(s) "
          f"({Path(images[0]).suffix})...")
    frames, roll = an.process_roll(images, exif)
    errors = [f for f in frames if f.get("error")]
    for fr in errors:
        print(f"  ERR {fr['stem']}: {fr['error']}")

    if roll and roll.get("vignette"):
        v, vi = roll["vignette"], roll.get("vignette_info") or {}
        print(f"Vignette: strength={v['strength']:.3f} radius={v['radius']:.3f} "
              f"steepness={v['steepness']:.3f} "
              f"(corner falloff {vi.get('corner_falloff', 0):.1%}, "
              f"residual {vi.get('residual')})")

    print()
    print("--- Invariants ---")
    violations = check_frame_invariants(frames, roll)
    if violations:
        for v in violations:
            print(f"  VIOLATION: {v}")
    else:
        print("  all invariants hold")

    print()
    print("--- Crop containment (HARD rule: never outside user crops) ---")
    containment = check_crop_containment(frames)
    for v in containment:
        print(f"  VIOLATION: {v}")

    print()
    print("--- Annotated frames (user corrections; informational) ---")
    report_annotated_frames(frames)

    print()
    print("--- Baseline diff ---")
    baseline = load_baseline()
    diff_frames = 0
    compared = 0
    winner_changed = False
    if not baseline:
        print("  no baseline_session/ yet - run generate_baseline.py after a")
        print("  user-approved debug-UI review to enable regression diffs")
    else:
        base_winner = next((b["film_base"]["global_winner_stem"]
                            for b in baseline.values()
                            if b.get("film_base")), None)
        if roll and base_winner and roll["winner_stem"] != base_winner:
            winner_changed = True
            print(f"  GLOBAL WINNER CHANGED: {roll['winner_stem']} vs {base_winner}")
        for fr in frames:
            if fr.get("error") or fr["stem"] not in baseline:
                continue
            compared += 1
            diffs = diff_frame_vs_baseline(fr, baseline[fr["stem"]])
            if diffs:
                diff_frames += 1
                print(f"  {fr['stem']}:")
                for d in diffs:
                    print(f"    {d}")
        print(f"  {diff_frames}/{compared} frame(s) differ from baseline")

    print()
    fail = bool(violations) or bool(errors) or bool(containment)
    warn = False
    if compared:
        frac = diff_frames / compared
        if winner_changed or frac > WARN_DIFF_FRAC:
            fail = True
        elif frac > PASS_DIFF_FRAC:
            warn = True

    verdict = "FAIL" if fail else ("WARN" if warn else "PASS")
    print(f"VERDICT: {verdict}")
    return 1 if fail else 0


if __name__ == "__main__":
    sys.exit(main())
